# Use an official Python runtime as a base image
FROM golang-windows-rs4-nanoserver-insider

#FROM golang-windows-rs4

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

WORKDIR /app 
RUN go build -o proxy.exe . 


# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

#CMD ["cmd"]

#Execute a ps script to add address to the interface for setting up the
#Instance Metadata Service request proxying
CMD .\setup.bat

