# Sample Dockerfile

# Indicates that the windowsservercore image will be used as the base image.
FROM microsoft/windowsservercore:1709

# Sets a command or process that will run each time a container is run from the new image.
CMD [ "cmd"]
